apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.198.155.195
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: guestbook-ui
