apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: guestbook
  name: guestbook-ui
  namespace: guestbook
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
status:
  loadBalancer:
    ingress:
      - ip: 20.198.155.195

  selector:
    app: guestbook-ui
